name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          # Install any project dependencies here
          echo "No dependencies to install"

      - name: Run tests
        run: |
          # Execute your test suite
          echo "Running tests..."
          echo "Tests passed!"

      - name: Build artifact
        run: |
          # Create a distributable artifact
          echo "Building application..."
          zip -r my-app.zip app/
          echo "Build complete."
          # Add a job for containerization
container_build:
  needs: build_and_test # This job will run after the build_and_test job succeeds
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: infrastructure/Dockerfile
        push: true
        tags: your-docker-username/your-app:latest

